from . import ksw_workshop_client
from . import res_partner
from . import ksw_workshop_request_type
from . import ksw_workshop_keyword_suggestion
from . import ksw_workshop_technician
from . import hr_employee
from . import ksw_workshop_part
from . import ksw_workshop_part_line
from . import ksw_workshop_labor_line
from . import ksw_workshop_request
from . import ksw_fleet_vehicle
